### ISSUE TITLE
Error BCryptOpenAlgorithmProvider & HASH_CTR

### ISSUE THREAD

**Issue by mrfearless** [secrary/idenLib#1]
Using command `idenlib "C:\SDKs\Windows Kits\8.1\Lib\winv6.3\um\x86"`
shows multiple error listings:
```
[!] Error 0xc000000d BCryptOpenAlgorithmProvider
[!] ERROR: c000000d HASH_CTR
```
Tried on a few different libraries. I'm using Windows 7 x64 just in case that is the issue.

**Comment by secrary** [comment]
`BCryptOpenAlgorithmProvider` function is a time intensive function, so I'm using `BCRYPT_HASH_REUSABLE_FLAG` to a reuse hashing object and according to [MS Docs](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptopenalgorithmprovider): `Windows Server 2008 R2, Windows 7, Windows Server 2008 and Windows Vista:  This flag is not supported.`

**Comment by secrary** [comment]
Now I'm considering [xxHash](https://github.com/Cyan4973/xxHash) instead of using `MD5` via `CNG` from MS

**Comment by secrary** [comment]
Now it uses `zstd` from compression and also works on win7
