### ISSUE TITLE
Building with dependencies

### ISSUE THREAD

**Issue by mrexodia** [secrary/idenLib#2]
Hello, today I wanted to try to add x64 support but there is currently no guide on how to build the submodules... For Zydis you can use a git submodule and simply include all the `.c` files in the project. Perhaps the same could be done for zstd, not sure. Could you update the readme with some guide on how to compile this project?

**Comment by secrary** [comment]
Just added `x64` support and also tried to use `submodules`

**Comment by mrexodia** [comment]
Works for me, thanks!
