### ISSUE TITLE
Multiple signatures for the same module?

### ISSUE THREAD

**Issue by aaaddress1** [secrary/idenLib#4]
Hey it's really nice tool. However in sometime, it's necessarily to identify x86 modules built by VS or x64 modules built by MinGW at the same time. Could you support multiple signatures for the same name module? like signatures of MSVCRT x86/x64 in the same SigEx fold. 

Thanks!

**Comment by secrary** [comment]
Good point.
At this moment, you should generate x86 signatures with x86 idenLib executable and x64 with x64 exec

**Comment by secrary** [comment]
Thank you for feedback,
See updated binary: https://github.com/secrary/idenLib/releases/tag/v0.3.1

**Comment by aaaddress1** [comment]
uh, so what's different in this update?

**Comment by aaaddress1** [comment]
oh nice, gotcha. I've read your code. it's helpful.
